# Generated by Django 4.1.7 on 2023-02-26 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starwarstasks', '0002_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='birth_year',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='people',
            name='created',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='people',
            name='edited',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='people',
            name='eye_color',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='people',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='people',
            name='hair_color',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='people',
            name='height',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='people',
            name='homeworld',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='people',
            name='mass',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='people',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='people',
            name='skin_color',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='people',
            name='url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
